### ISSUE TITLE
lightbug_http pacakge support in VSCode

### ISSUE THREAD

**Issue by ajshedivy** [saviorand/lightbug_http#73]
NOTE: I am new to the modular ecosystem so I appreciate you help and patience :grin:

I followed the instructions to setup a `mojoproject` using magic:

1. Create mojo project

```bash
magic init lightbug-test --format mojoproject
```

2. Add community channel to `mojoproject.toml`
```toml
[project]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community"]
```

3. Add lightbug_http package

```
magic add lightbug_http
```

`mojoproject.toml`:
```toml
[project]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community"]
name = "lightbug-test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
lightbug_http = ">=0.1.5,<0.2"

```

Everything up to this point works great, but when I create a mojo file in vscode and import modules from `lightbug_http`, I get the following error:

```
unable to locate module 'lightbug_http' mojo
```
![image](https://github.com/user-attachments/assets/cdfe54b1-90e4-47b5-bd3f-c37696bb9b29)

I am able to run the server just fine using `magic run mojo` 
![image](https://github.com/user-attachments/assets/b2abb291-55d0-4b97-aa9c-2fc454e8a661)

Is there a setup step or config I am missing that would resolve the import errors with mojo? Is there a way to select a "magic environment" like in python where you can activate a specific environment in vscode? 

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Chip: Apple M3 Pro
